### ISSUE TITLE
Demo content bugs

### ISSUE THREAD

**Issue by landsman** [BurdaMagazinOrg/thunder-distribution#199]
Hi,

1) This is screenshot is from today fresh install (infinite theme, demo content):
![fresh-install](https://cloud.githubusercontent.com/assets/3184228/21567796/533a4684-ceaf-11e6-89a7-9dccc2fb2167.png)
... after reload exception is gone but this is looking very oddly.

2) In demo content is bug about ajax paginator. 
Requested url is "/home" but this is url or alias not exist. Home is in code(!) here: https://github.com/BurdaMagazinOrg/infinite-module/blob/8.x-1.x/src/Plugin/Block/InfiniteLazyLoadingSimple.php#L54

![snimek obrazovky 2016-12-30 v 16 47 32](https://cloud.githubusercontent.com/assets/3184228/21567845/c98aa5ea-ceaf-11e6-8efe-cbe719d48186.png)

Is possible create more stable demo content for new members?

**Environment:**
- OS X 10.12.2 (16C67)
- MAMP PRO with OPcache
- npm 3.10.8
- php 7.0.12
- mysql 5.6.33

**Comment by goldquest** [comment]
Thanks for the issue. Will have a look at it.

**Comment by goldquest** [comment]
Blazy beta6 is not compatible with slick at the moment. See Drupal issue here: https://www.drupal.org/node/2841316.

**Comment by landsman** [comment]
OK, next thing is demo data setup.

**Comment by landsman** [comment]
I don't know how this exception can related with Blazy&Slick issue but this shows after few reloads on article detail - demo content:

`Notice: Array to string conversion in Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (line 68 of modules/contrib/infinite_module/src/Plugin/Block/InfiniteLazyLoadingSimple.php).
Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (Line: 203)
Drupal\block\BlockViewBuilder::preRender(Array)
call_user_func('Drupal\block\BlockViewBuilder::preRender', Array) (Line: 376)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 474)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 58)
__TwigTemplate_35653759f08030f5b2154e41b40216a102efcf2c9b00b4dd474b1f9bfce108c4->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/contrib/infinite_theme/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 574)
Drupal\Core\Template\TwigExtension->renderVar(Array) (Line: 181)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->block_article_footer_blocks_full(Array, Array) (Line: 215)
Twig_Template->displayBlock('article_footer_blocks_full', Array, Array, 1) (Line: 279)
Twig_Template->renderBlock('article_footer_blocks_full', Array, Array) (Line: 115)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/custom/marianne/templates/node/node--article--full.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 61)
Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 140)
Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.view', Object) (Line: 149)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 38)
Drupal\webprofiler\StackMiddleware\WebprofilerMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
Notice: Array to string conversion in Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (line 68 of modules/contrib/infinite_module/src/Plugin/Block/InfiniteLazyLoadingSimple.php).
Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (Line: 203)
Drupal\block\BlockViewBuilder::preRender(Array)
call_user_func('Drupal\block\BlockViewBuilder::preRender', Array) (Line: 376)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 474)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 58)
__TwigTemplate_35653759f08030f5b2154e41b40216a102efcf2c9b00b4dd474b1f9bfce108c4->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/contrib/infinite_theme/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 474)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 184)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->block_article_footer_blocks_full(Array, Array) (Line: 215)
Twig_Template->displayBlock('article_footer_blocks_full', Array, Array, 1) (Line: 279)
Twig_Template->renderBlock('article_footer_blocks_full', Array, Array) (Line: 115)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/custom/marianne/templates/node/node--article--full.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 61)
Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 140)
Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.view', Object) (Line: 149)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 38)
Drupal\webprofiler\StackMiddleware\WebprofilerMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
Notice: Array to string conversion in Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (line 68 of modules/contrib/infinite_module/src/Plugin/Block/InfiniteLazyLoadingSimple.php).
Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (Line: 203)
Drupal\block\BlockViewBuilder::preRender(Array)
call_user_func('Drupal\block\BlockViewBuilder::preRender', Array) (Line: 376)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 474)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 58)
__TwigTemplate_35653759f08030f5b2154e41b40216a102efcf2c9b00b4dd474b1f9bfce108c4->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/contrib/infinite_theme/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 574)
Drupal\Core\Template\TwigExtension->renderVar(Array) (Line: 181)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->block_article_footer_blocks_full(Array, Array) (Line: 215)
Twig_Template->displayBlock('article_footer_blocks_full', Array, Array) (Line: 120)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/custom/marianne/templates/node/node--article--full.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 61)
Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 140)
Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.view', Object) (Line: 149)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 38)
Drupal\webprofiler\StackMiddleware\WebprofilerMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)
Notice: Array to string conversion in Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (line 68 of modules/contrib/infinite_module/src/Plugin/Block/InfiniteLazyLoadingSimple.php).
Drupal\infinite_base\Plugin\Block\InfiniteLazyLoadingSimple->build() (Line: 203)
Drupal\block\BlockViewBuilder::preRender(Array)
call_user_func('Drupal\block\BlockViewBuilder::preRender', Array) (Line: 376)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 474)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 58)
__TwigTemplate_35653759f08030f5b2154e41b40216a102efcf2c9b00b4dd474b1f9bfce108c4->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/contrib/infinite_theme/templates/field/field.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('field', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array) (Line: 474)
Drupal\Core\Template\TwigExtension->escapeFilter(Object, Array, 'html', NULL, 1) (Line: 184)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->block_article_footer_blocks_full(Array, Array) (Line: 215)
Twig_Template->displayBlock('article_footer_blocks_full', Array, Array) (Line: 120)
__TwigTemplate_5c615c1550dc016bed4056609b91bd5ae3605593bb2791a5e1240a20844d203d->doDisplay(Array, Array) (Line: 432)
Twig_Template->displayWithErrorHandling(Array, Array) (Line: 403)
Twig_Template->display(Array) (Line: 411)
Twig_Template->render(Array) (Line: 64)
twig_render_template('themes/custom/marianne/templates/node/node--article--full.html.twig', Array) (Line: 384)
Drupal\Core\Theme\ThemeManager->render('node', Array) (Line: 435)
Drupal\Core\Render\Renderer->doRender(Array, ) (Line: 195)
Drupal\Core\Render\Renderer->render(Array, ) (Line: 226)
Drupal\Core\Render\MainContent\HtmlRenderer->Drupal\Core\Render\MainContent\{closure}() (Line: 574)
Drupal\Core\Render\Renderer->executeInRenderContext(Object, Object) (Line: 227)
Drupal\Core\Render\MainContent\HtmlRenderer->prepare(Array, Object, Object) (Line: 117)
Drupal\Core\Render\MainContent\HtmlRenderer->renderResponse(Array, Object, Object) (Line: 90)
Drupal\Core\EventSubscriber\MainContentViewSubscriber->onViewRenderArray(Object, 'kernel.view', Object)
call_user_func(Array, Object, 'kernel.view', Object) (Line: 61)
Symfony\Component\EventDispatcher\Debug\WrappedListener->__invoke(Object, 'kernel.view', Object) (Line: 111)
Drupal\Component\EventDispatcher\ContainerAwareEventDispatcher->dispatch('kernel.view', Object) (Line: 140)
Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcher->dispatch('kernel.view', Object) (Line: 149)
Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object, 1) (Line: 64)
Symfony\Component\HttpKernel\HttpKernel->handle(Object, 1, 1) (Line: 57)
Drupal\Core\StackMiddleware\Session->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\KernelPreHandle->handle(Object, 1, 1) (Line: 99)
Drupal\page_cache\StackMiddleware\PageCache->pass(Object, 1, 1) (Line: 78)
Drupal\page_cache\StackMiddleware\PageCache->handle(Object, 1, 1) (Line: 47)
Drupal\Core\StackMiddleware\ReverseProxyMiddleware->handle(Object, 1, 1) (Line: 38)
Drupal\webprofiler\StackMiddleware\WebprofilerMiddleware->handle(Object, 1, 1) (Line: 50)
Drupal\Core\StackMiddleware\NegotiationMiddleware->handle(Object, 1, 1) (Line: 23)
Stack\StackedHttpKernel->handle(Object, 1, 1) (Line: 652)
Drupal\Core\DrupalKernel->handle(Object) (Line: 19)`

**Comment by landsman** [comment]
4. Here is another bug i think:

![snimek obrazovky 2017-01-06 v 13 14 35](https://cloud.githubusercontent.com/assets/3184228/21717566/21b36466-d412-11e6-845b-9a2200c98f45.png)

What module is not enabled here?

**Comment by goldquest** [comment]
3 is fixed here: https://github.com/BurdaMagazinOrg/infinite-module/pull/23

**Comment by goldquest** [comment]
Regarding 2)
Check out this PR: https://github.com/BurdaMagazinOrg/infinite-module/pull/24
This will stop trying to load something, if we reached the oldest article.

**Comment by goldquest** [comment]
4 is wierd. Infinite should install these promotion options, which are missing.

**Comment by landsman** [comment]
@goldquest Thank you for reply and fixes. Yes 4. looks strange. It is on fresh install of Thunder. Can I test something else for it?

**Comment by landsman** [comment]
I was see to https://github.com/BurdaMagazinOrg/infinite-module/blob/8.x-1.x/src/Plugin/Block/InfiniteLazyLoadingSimple.php#L54 can you replace with: 
```$lazy_loading_url = \Drupal::request()->getSchemeAndHttpHost() . '?page=0';``` ?

**Comment by goldquest** [comment]
@landsman this is no longer necessary, when the PR is merged

**Comment by landsman** [comment]
ok

**Comment by goldquest** [comment]
So we decided to actually include a view, which will be inserted, after the oldest article is reached.

**Comment by landsman** [comment]
Do you know something about 4. ?

**Comment by goldquest** [comment]
4 is now also fixed: https://github.com/BurdaMagazinOrg/infinite-module/pull/25
Please regard, that we removed the broken promotion options, but don't have an update hook here, since we don't want to break existing installs. You would have to remove them manually.

**Comment by landsman** [comment]
Great, thank you!
