### ISSUE TITLE
SEO title field

### ISSUE THREAD

**Issue by landsman** [BurdaMagazinOrg/thunder-distribution#201]
Hi, I am looking to “SEO title” field in "Add article”. It’s annoying write seo title manually & that is required item. What about some JS / AJAX what can translate “Title” filed to “SEO title” dynamic?

**Comment by goldquest** [comment]
Thanks for the proposal. We put it on the feature list.

**Comment by dbosen** [comment]
Closing this on github and reopen it on drupal.org https://www.drupal.org/node/2899061
