### ISSUE TITLE
Author page

### ISSUE THREAD

**Issue by landsman** [BurdaMagazinOrg/thunder-distribution#208]
Hello,
template "author-user.html.twig" not including on author's page (e.g., example.com/user/123) in default install of Thunder with "demo data". Default view "infinite_author" exist. 

![snimek obrazovky 2017-01-16 v 11 10 04](https://cloud.githubusercontent.com/assets/3184228/21978783/5a986b60-dbdc-11e6-8cda-314c88a31985.png)

Can you look on this please?

**Comment by goldquest** [comment]
Apparently the first_name and last_name is missing in the user fields. We have to add them.

**Comment by goldquest** [comment]
As another dev suggested in another module: we should use the `user.displayName` method, to show the username. This can be overridden by hooks. That way, there is always a username visible.

**Comment by landsman** [comment]
Is standard Drupal method?
I want make priorty: 
1. name, surname 
2. nickname

**Comment by goldquest** [comment]
Yes. You can implement a hook to provide this: https://api.drupal.org/api/drupal/core!modules!user!user.api.php/function/hook_user_format_name_alter/8.2.x

**Comment by landsman** [comment]
Thank you @goldquest !
