### ISSUE TITLE
Cannot update thunder to 1.1 via composer

### ISSUE THREAD

**Issue by rthideaway** [BurdaMagazinOrg/thunder-distribution#274]
4 days ago there was official release of Thunder version 8.1.1 on drupal.org but currently it's still not possible to include this package via composer (package burdamagazinorg/thunder with vesion 1.1 is not currently on packagist).

It is possible to include drupal/thunder package which is unfortunately not sufficient for us, since its composer json is not containing list of drupal modules, instead it takes all packages with it and you have no control over it. You are unable set custom paths for drupal/* packages. And finally it ends up by default in vendor, since the package type is "project".

The question would be, if we could expect the version 1.1 on packagist soon. Or should I just add this repository to composer json for now, instead of getting the package from packagist?

**Comment by rthideaway** [comment]
solved temporarily by requiring direct commit
`
composer require burdamagazinorg/thunder:dev-master#d64a5e5394856be2c33b95b8b283e1015a55f249
`

**Comment by dbosen** [comment]
Hello,
thanks for reporting this. We now pushed the tag to packagist.
