### ISSUE TITLE
Remove Instyle strings from code

### ISSUE THREAD

**Issue by hctom** [BurdaMagazinOrg/thunder-distribution#41]
Currently there are several Instyle occurences hard-coded into the code/config of the infinite modules/theme:
- In default external links filter config (`infinite-module/config/install/infinite_base.filter_external_links.yml`)
- In newsletter template's CSS classes (with corresponding CSS styles in `infinite-global.css`)
- In socials bar template, all links point to InStyle social network pages
- In `infinite_views/config/optional/block.block.archivetreeperyearmonth.yml`the `instyle_infinite` theme is required (but that may be no problem, because it is an optional config)
- In `infinite_views/config/optional/views.view.infinite_author.yml` the view title says "Instyle Autor"
- In `infinite-theme/js/infinite/views/base/base-newsletter-view.js` there is a newsletter ID hard-coded based on `.instyle-men` CSS class, even though the next line indicates that this might be set via `newsletter-group-id` data attribute

There are also some more, but those appear in example context and so might be ignored.

I'd appreciate if you take a look, which of the others might be removed.

**Comment by dbosen** [comment]
We have a pull requests open for decoupling social bar. I will file tickets in the instyle jira for the other issues
