### ISSUE TITLE
Latest dev of Entity browser causing problems with profile installation.

### ISSUE THREAD

**Issue by rthideaway** [BurdaMagazinOrg/thunder-distribution#57]
Module "entity_browser" should be most probably locked to "8.x-1.0-alpha6" before implementation of abstract method "prepareEntities" in WidgetBase in file entity_browser\src\WidgetBase.php

Dropzone is extending this class, but since the module is older, it is not containing that method, and this installing thunder distribution, which was build by composer will result in fatal error:

`PHP Fatal error:  Class Drupal\\dropzonejs_eb_widget\\Plugin\\EntityBrowser\\Widget\\DropzoneJsEbWidget contains 1 abstract method and must therefore be declared abstract or implement the remaining methods (Drupal\\entity_browser\\WidgetBase::prepareEntities) in thunderinf\\docroot\\modules\\contrib\\dropzonejs\\modules\\eb_widget\\src\\Plugin\\EntityBrowser\\Widget\\DropzoneJsEbWidget.php on line 28, referer: http://local.thunderinf.at/core/install.php?rewrite=ok&profile=thunder&langcode=en&id=1&op=start`

**Comment by dbosen** [comment]
Hello!
We are working on a patch for dropzonejs and this patch will be included in our next release

**Comment by rthideaway** [comment]
Cool, thank you! And will it solve also the following error? :)

`Drupal\\Core\\Config\\PreExistingConfigException: Configuration objects (field.storage.taxonomy_term.field_header_media, field.storage.taxonomy_term.field_header_title) provided by thunder_taxonomy already exist in active configuration in thunderinf\\docroot\\core\\lib\\Drupal\\Core\\Config\\PreExistingConfigException.php on line 65, referer: http://local.thunderinf.at/core/install.php?rewrite=ok&profile=thunder&langcode=en&id=1&op=start`

I downgraded entity_browser to 8.x-1.0-alpha6, but now I have that kind of error

**Comment by maosmurf** [comment]
Currently our thunder installation reports "Dropzone library missing: Dropzonejs requires the dropzone.min.js library. Download it (https://github.com/enyo/dropzone) and place it in the libraries folder (/libraries)", and the frontend renders with JS-errors.

enyo/dropzone was removed in d9904287841f2baac97d4bd0992e977ff1ca1e73.

What is the best way to handle your updates, where you remove dependencies?

**Comment by rthideaway** [comment]
working with latest dev, so closing...

**Comment by dbosen** [comment]
@maosmurf that dependency was not removed, that has been a hicup during development. The last stable beta release should not have this problem, we now install frontend libraries with bower, so you might need npm if you build the distribution with composer.
Generally we try to avoid to remove dependencies, but during the beta phase this might still happen. If that is happening, we will communicate that in the readme. 
If the removed dependency is a drupal contrib module you want use, you can just add the requirement to your own drush make file or composer.json.
