### ISSUE TITLE
Latest dev of Thunder and dropzonejs fails the build

### ISSUE THREAD

**Issue by meramo** [BurdaMagazinOrg/thunder-distribution#70]
When building a distro from the thunder infrastructure repository (via bin/robo site:install local) have two problems with dropzonejs module.

For the record, grabbing the latest one with 
`composer create-project burdamagazinorg/thunder-infrastructure . --stability dev --no-interaction`

1. Composer install complains the patch could not be applied
<img width="684" alt="dropzone" src="https://cloud.githubusercontent.com/assets/459257/17478799/f4db5bae-5d76-11e6-9840-f2ad04b7adfb.png">

2. The installation process never finishes because of the following error
<img width="684" alt="dropzone" src="https://cloud.githubusercontent.com/assets/459257/17478823/23eca84e-5d77-11e6-8623-032744aeaab9.png">

When using the distro downloaded from Drupal.org everything is fine though. The installed version there is 1.0-alpha2 and produces no errors.

**Comment by dbosen** [comment]
we fixed this in the current dev version of burdamagazinorg/thunder, for a quick fix you can do a
```
composer dependency-cleanup
composer require burdamagazinorg/thunder:dev-8.x-1.x
```
or wait for our next beta release which we will do today and just do a composer update

**Comment by meramo** [comment]
Cool, thanks! So I think it can be closed now.
